import { randomBytes, randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import QRCode from 'qrcode';
import { z } from 'zod';
import { pool, withTransaction } from '../db/pool.js';
import { actorOf, assertStoreScope, assertVendorScope } from '../core/scope.js';
import { badRequest, notFound } from '../core/errors.js';
import { paginationMeta, paginationSchema } from '../core/pagination.js';
import { privacyHash } from '../core/security.js';
import { env } from '../config/env.js';
import { writeAudit } from '../core/audit.js';

const campaignInput=z.object({storeId:z.uuid(),vendorId:z.uuid().nullable().optional(),name:z.string().trim().min(2).max(200),slug:z.string().trim().min(2).max(200),description:z.string().trim().max(5000).default(''),campaignType:z.enum(['daily_deal','weekly','limited','seasonal','giveaway','sponsored','qr','other']),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),budget:z.number().min(0).nullable().optional(),goals:z.record(z.string(),z.unknown()).default({}),targeting:z.record(z.string(),z.unknown()).default({})}).refine(v=>new Date(v.endsAt)>new Date(v.startsAt),{path:['endsAt'],message:'Bitmə tarixi başlama tarixindən sonra olmalıdır'});
const couponInput=z.object({storeId:z.uuid(),vendorId:z.uuid().nullable().optional(),campaignId:z.uuid().nullable().optional(),name:z.string().trim().min(2).max(200),codePrefix:z.string().trim().min(2).max(12).default('DB'),discountType:z.enum(['percentage','fixed_amount','free_shipping','gift']),discountValue:z.number().min(0),minimumOrder:z.number().min(0).default(0),quantityLimit:z.number().int().positive().nullable().optional(),perUserLimit:z.number().int().positive().default(1),startsAt:z.iso.datetime(),expiresAt:z.iso.datetime(),rules:z.record(z.string(),z.unknown()).default({})}).refine(v=>v.discountType!=='percentage'||v.discountValue<=100,{path:['discountValue'],message:'Faiz 100-dən çox ola bilməz'});
const safeUrl=z.url().refine(value=>['http:','https:'].includes(new URL(value).protocol),'Yalnız HTTP/HTTPS URL qəbul edilir');
const qrInput=z.object({storeId:z.uuid(),vendorId:z.uuid().nullable().optional(),campaignId:z.uuid().nullable().optional(),name:z.string().trim().min(2).max(200),qrType:z.enum(['product','coupon','reward','lead','social','event','survey','store','smart']),targetUrl:safeUrl,productId:z.uuid().nullable().optional(),couponId:z.uuid().nullable().optional(),rewardPoints:z.number().int().positive().nullable().optional(),scanLimit:z.number().int().positive().nullable().optional(),perUserLimit:z.number().int().positive().default(1),startsAt:z.iso.datetime().nullable().optional(),expiresAt:z.iso.datetime().nullable().optional(),rules:z.record(z.string(),z.unknown()).default({})}).superRefine((v,c)=>{if(v.qrType==='product'&&!v.productId)c.addIssue({code:'custom',path:['productId'],message:'Məhsul tələb olunur'});if(v.qrType==='coupon'&&!v.couponId)c.addIssue({code:'custom',path:['couponId'],message:'Kupon tələb olunur'});if(v.qrType==='reward'&&!v.rewardPoints)c.addIssue({code:'custom',path:['rewardPoints'],message:'Bonus xalı tələb olunur'});});
const campaignStatusInput=z.object({status:z.enum(['draft','scheduled','active','paused','ended','cancelled'])});
const recordStatusInput=z.object({status:z.enum(['draft','active','inactive','archived'])});
async function scope(actor:ReturnType<typeof actorOf>,storeId:string,vendorId?:string|null){assertStoreScope(actor,storeId);if(actor.vendorIds.length&&!vendorId)throw badRequest('VENDOR_REQUIRED','Satıcı hesabı vendor seçməlidir');if(vendorId){const vendor=await pool.query('SELECT store_id FROM vendors WHERE id=$1 AND deleted_at IS NULL',[vendorId]);if(!vendor.rows[0]||vendor.rows[0].store_id!==storeId)throw notFound('Satıcı');if(actor.vendorIds.length)assertVendorScope(actor,vendorId);}}

export async function marketingRoutes(app:FastifyInstance):Promise<void>{
  app.get('/campaigns',{preHandler:app.requirePermission('campaigns.read')},async(request)=>{const q=paginationSchema.parse(request.query);const actor=actorOf(request);const params:unknown[]=[];const where=['1=1'];if(actor.vendorIds.length){params.push(actor.vendorIds);where.push(`vendor_id=ANY($${params.length}::uuid[])`);}else if(!actor.isSuperAdmin){params.push(actor.storeIds);where.push(`store_id=ANY($${params.length}::uuid[])`);}if(q.search){params.push(`%${q.search}%`);where.push(`name ILIKE $${params.length}`);}if(q.status){params.push(q.status);where.push(`status::text=$${params.length}`);}params.push(q.limit,(q.page-1)*q.limit);const r=await pool.query(`SELECT *,count(*) OVER()::int AS total_count FROM campaigns WHERE ${where.join(' AND ')} ORDER BY starts_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);const total=Number(r.rows[0]?.total_count??0);return{data:r.rows.map(({total_count:_,...x})=>x),meta:paginationMeta(q.page,q.limit,total)};});
  app.post('/campaigns',{preHandler:app.requirePermission('campaigns.manage')},async(request,reply)=>{const i=campaignInput.parse(request.body);const a=actorOf(request);await scope(a,i.storeId,i.vendorId);const r=await pool.query(`INSERT INTO campaigns(store_id,vendor_id,name,slug,description,campaign_type,starts_at,ends_at,budget,goals,targeting,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[i.storeId,i.vendorId??null,i.name,i.slug,i.description,i.campaignType,i.startsAt,i.endsAt,i.budget??null,JSON.stringify(i.goals),JSON.stringify(i.targeting),a.userId]);return reply.code(201).send({data:r.rows[0]});});
  app.patch('/campaigns/:id/status',{preHandler:app.requirePermission('campaigns.manage')},async(request)=>{const id=z.uuid().parse((request.params as{id:string}).id);const input=campaignStatusInput.parse(request.body);const actor=actorOf(request);const current=await pool.query('SELECT * FROM campaigns WHERE id=$1',[id]);const row=current.rows[0];if(!row)throw notFound('Kampaniya');await scope(actor,row.store_id,row.vendor_id);const data=await withTransaction(async(client)=>{const result=await client.query('UPDATE campaigns SET status=$2::campaign_status WHERE id=$1 RETURNING *',[id,input.status]);await writeAudit(client,{actorUserId:actor.userId,storeId:row.store_id,vendorId:row.vendor_id,action:'campaign.status.update',entityType:'campaign',entityId:id,beforeData:{status:row.status},afterData:{status:input.status},requestId:request.id});return result.rows[0];});return{data};});
  app.get('/coupons',{preHandler:app.requirePermission('coupons.read')},async(request)=>{const q=paginationSchema.parse(request.query);const a=actorOf(request);const params:unknown[]=[];const where=['1=1'];if(a.vendorIds.length){params.push(a.vendorIds);where.push(`vendor_id=ANY($${params.length}::uuid[])`);}else if(!a.isSuperAdmin){params.push(a.storeIds);where.push(`store_id=ANY($${params.length}::uuid[])`);}if(q.search){params.push(`%${q.search}%`);where.push(`(name ILIKE $${params.length} OR code_prefix ILIKE $${params.length})`);}if(q.status){params.push(q.status);where.push(`status::text=$${params.length}`);}params.push(q.limit,(q.page-1)*q.limit);const r=await pool.query(`SELECT *,count(*) OVER()::int AS total_count FROM coupons WHERE ${where.join(' AND ')} ORDER BY created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);const total=Number(r.rows[0]?.total_count??0);return{data:r.rows.map(({total_count:_,...x})=>x),meta:paginationMeta(q.page,q.limit,total)};});
  app.post('/coupons',{preHandler:app.requirePermission('coupons.manage')},async(request,reply)=>{const i=couponInput.parse(request.body);const a=actorOf(request);await scope(a,i.storeId,i.vendorId);const r=await pool.query(`INSERT INTO coupons(store_id,vendor_id,campaign_id,name,code_prefix,discount_type,discount_value,minimum_order,quantity_limit,per_user_limit,starts_at,expires_at,rules) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[i.storeId,i.vendorId??null,i.campaignId??null,i.name,i.codePrefix.toUpperCase(),i.discountType,i.discountValue,i.minimumOrder,i.quantityLimit??null,i.perUserLimit,i.startsAt,i.expiresAt,JSON.stringify(i.rules)]);return reply.code(201).send({data:r.rows[0]});});
  app.patch('/coupons/:id/status',{preHandler:app.requirePermission('coupons.manage')},async(request)=>{const id=z.uuid().parse((request.params as{id:string}).id);const input=recordStatusInput.parse(request.body);const actor=actorOf(request);const current=await pool.query('SELECT * FROM coupons WHERE id=$1',[id]);const row=current.rows[0];if(!row)throw notFound('Kupon');await scope(actor,row.store_id,row.vendor_id);const data=await withTransaction(async(client)=>{const result=await client.query('UPDATE coupons SET status=$2::record_status WHERE id=$1 RETURNING *',[id,input.status]);await writeAudit(client,{actorUserId:actor.userId,storeId:row.store_id,vendorId:row.vendor_id,action:'coupon.status.update',entityType:'coupon',entityId:id,beforeData:{status:row.status},afterData:{status:input.status},requestId:request.id});return result.rows[0];});return{data};});
  app.get('/qr',{preHandler:app.requirePermission('qr.read')},async(request)=>{const q=paginationSchema.parse(request.query);const a=actorOf(request);const params:unknown[]=[];const where=['1=1'];if(a.vendorIds.length){params.push(a.vendorIds);where.push(`vendor_id=ANY($${params.length}::uuid[])`);}else if(!a.isSuperAdmin){params.push(a.storeIds);where.push(`store_id=ANY($${params.length}::uuid[])`);}if(q.search){params.push(`%${q.search}%`);where.push(`(name ILIKE $${params.length} OR code ILIKE $${params.length})`);}if(q.status){params.push(q.status);where.push(`status::text=$${params.length}`);}params.push(q.limit,(q.page-1)*q.limit);const r=await pool.query(`SELECT *,count(*) OVER()::int AS total_count FROM qr_codes WHERE ${where.join(' AND ')} ORDER BY created_at DESC LIMIT $${params.length-1} OFFSET $${params.length}`,params);const total=Number(r.rows[0]?.total_count??0);return{data:r.rows.map(({total_count:_,...x})=>x),meta:paginationMeta(q.page,q.limit,total)};});
  app.post('/qr',{preHandler:app.requirePermission('qr.manage')},async(request,reply)=>{const i=qrInput.parse(request.body);const a=actorOf(request);await scope(a,i.storeId,i.vendorId);const code=`DB-${randomBytes(9).toString('base64url')}`;const r=await pool.query(`INSERT INTO qr_codes(store_id,vendor_id,campaign_id,code,name,qr_type,target_url,product_id,coupon_id,reward_points,scan_limit,per_user_limit,starts_at,expires_at,rules,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[i.storeId,i.vendorId??null,i.campaignId??null,code,i.name,i.qrType,i.targetUrl,i.productId??null,i.couponId??null,i.rewardPoints??null,i.scanLimit??null,i.perUserLimit,i.startsAt??null,i.expiresAt??null,JSON.stringify(i.rules),a.userId]);return reply.code(201).send({data:r.rows[0],scanUrl:`${env.PUBLIC_ORIGIN}/q/${code}`});});
  app.patch('/qr/:id/status',{preHandler:app.requirePermission('qr.manage')},async(request)=>{const id=z.uuid().parse((request.params as{id:string}).id);const input=recordStatusInput.parse(request.body);const actor=actorOf(request);const current=await pool.query('SELECT * FROM qr_codes WHERE id=$1',[id]);const row=current.rows[0];if(!row)throw notFound('QR');await scope(actor,row.store_id,row.vendor_id);const data=await withTransaction(async(client)=>{const result=await client.query('UPDATE qr_codes SET status=$2::record_status WHERE id=$1 RETURNING *',[id,input.status]);await writeAudit(client,{actorUserId:actor.userId,storeId:row.store_id,vendorId:row.vendor_id,action:'qr.status.update',entityType:'qr_code',entityId:id,beforeData:{status:row.status},afterData:{status:input.status},requestId:request.id});return result.rows[0];});return{data};});
  app.get('/qr/:id/svg',{preHandler:app.requirePermission('qr.read')},async(request,reply)=>{const id=z.uuid().parse((request.params as{id:string}).id);const a=actorOf(request);const r=await pool.query('SELECT * FROM qr_codes WHERE id=$1',[id]);const row=r.rows[0];if(!row)throw notFound('QR');await scope(a,row.store_id,row.vendor_id);const svg=await QRCode.toString(`${env.PUBLIC_ORIGIN}/q/${row.code}`,{type:'svg',errorCorrectionLevel:'H',margin:2,width:640});return reply.type('image/svg+xml').send(svg);});

  app.get('/scan/:code',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(request,reply)=>{const code=z.string().min(5).max(100).parse((request.params as{code:string}).code);let userId:string|null=null;try{await request.jwtVerify({onlyCookie:true});userId=request.user.sub;}catch{userId=null;}let anonymousId=request.cookies['db_anonymous'];if(!userId){if(!anonymousId||!z.uuid().safeParse(anonymousId).success)anonymousId=randomUUID();reply.setCookie('db_anonymous',anonymousId,{path:'/',httpOnly:true,sameSite:'lax',secure:env.NODE_ENV==='production',maxAge:31_536_000});}
    const target=await withTransaction(async(client)=>{const locked=await client.query(`SELECT * FROM qr_codes WHERE code=$1 FOR UPDATE`,[code]);const q=locked.rows[0];if(!q||q.status!=='active')throw notFound('QR');const now=Date.now();if(q.starts_at&&new Date(q.starts_at).getTime()>now)throw badRequest('QR_NOT_STARTED','QR kampaniyası hələ başlamayıb');if(q.expires_at&&new Date(q.expires_at).getTime()<now)throw badRequest('QR_EXPIRED','QR kodun vaxtı bitib');if(q.scan_limit&&Number(q.scan_count)>=q.scan_limit)throw badRequest('QR_LIMIT_REACHED','QR istifadə limiti bitib');const identity=userId??anonymousId!;const previous=await client.query(`SELECT count(*)::int AS count FROM qr_scans WHERE qr_code_id=$1 AND ${userId?'user_id=$2':'anonymous_id=$2'}`,[q.id,identity]);if(previous.rows[0].count>=q.per_user_limit)throw badRequest('QR_USER_LIMIT','Bu QR üçün şəxsi limit bitib');await client.query(`INSERT INTO qr_scans(qr_code_id,user_id,anonymous_id,ip_hash,referrer,user_agent,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)`,[q.id,userId,userId?null:anonymousId,privacyHash(request.ip,env.COOKIE_SECRET),request.headers.referer??null,request.headers['user-agent']??null,JSON.stringify({acceptLanguage:request.headers['accept-language']})]);await client.query('UPDATE qr_codes SET scan_count=scan_count+1 WHERE id=$1',[q.id]);if(userId&&q.qr_type==='reward'&&q.reward_points){const account=await client.query(`INSERT INTO loyalty_accounts(user_id,store_id,balance,lifetime_earned) VALUES($1,$2,$3,$3) ON CONFLICT(user_id,store_id) DO UPDATE SET balance=loyalty_accounts.balance+$3,lifetime_earned=loyalty_accounts.lifetime_earned+$3,updated_at=now() RETURNING balance`,[userId,q.store_id,q.reward_points]);await client.query(`INSERT INTO loyalty_ledger(user_id,store_id,points,reason,reference_type,reference_id,balance_after,idempotency_key) VALUES($1,$2,$3,'QR bonusu','qr',$4,$5,$6)`,[userId,q.store_id,q.reward_points,q.id,account.rows[0].balance,`qr:${q.id}:${userId}`]);}if(userId&&q.qr_type==='coupon'&&q.coupon_id){const coupon=await client.query('SELECT * FROM coupons WHERE id=$1',[q.coupon_id]);if(coupon.rows[0])await client.query(`INSERT INTO user_coupons(coupon_id,user_id,unique_code,acquired_via,expires_at,metadata) VALUES($1,$2,$3,'qr',$4,$5)`,[q.coupon_id,userId,`${coupon.rows[0].code_prefix}-${randomBytes(6).toString('hex').toUpperCase()}`,coupon.rows[0].expires_at,JSON.stringify({qrCodeId:q.id})]);}return q.target_url;});return reply.redirect(target);});
}
